// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

package org.devolpex.backend.stubs.main;

public final class Main {
  private Main() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmain.proto\022\037org.devolpex.backend.stubs" +
      ".main\032\014client.proto\032\rchambre.proto\032\021rese" +
      "rvation.proto2^\n\022ReservationService\022H\n\024F" +
      "etchReservationList\022\027.GetReservationsLis" +
      "tREQ\032\027.GetReservationsListRESB\002P\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor(),
          org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor(),
          org.devolpex.backend.stubs.reservation.ReservationOuterClass.getDescriptor(),
        });
    org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor();
    org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor();
    org.devolpex.backend.stubs.reservation.ReservationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
