apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.grpcNodePort }}
      {{- end }}
    - port: {{ .Values.service.actuatorPort }}
      targetPort: actuator
      protocol: TCP
      name: actuator
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.actuatorNodePort }}
      {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
