// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package org.devolpex.backend.stubs.shared;

/**
 * <pre>
 * Pageable message definition
 * </pre>
 *
 * Protobuf type {@code PageablePRT}
 */
public  final class PageablePRT extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PageablePRT)
    PageablePRTOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PageablePRT.newBuilder() to construct.
  private PageablePRT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PageablePRT() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PageablePRT();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PageablePRT(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pageNumber_ = input.readInt32();
            break;
          }
          case 16: {

            pageSize_ = input.readInt32();
            break;
          }
          case 24: {

            offset_ = input.readInt64();
            break;
          }
          case 32: {

            paged_ = input.readBool();
            break;
          }
          case 40: {

            unpaged_ = input.readBool();
            break;
          }
          case 50: {
            org.devolpex.backend.stubs.shared.SortPRT.Builder subBuilder = null;
            if (sort_ != null) {
              subBuilder = sort_.toBuilder();
            }
            sort_ = input.readMessage(org.devolpex.backend.stubs.shared.SortPRT.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sort_);
              sort_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.devolpex.backend.stubs.shared.Shared.internal_static_PageablePRT_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.devolpex.backend.stubs.shared.Shared.internal_static_PageablePRT_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.devolpex.backend.stubs.shared.PageablePRT.class, org.devolpex.backend.stubs.shared.PageablePRT.Builder.class);
  }

  public static final int PAGENUMBER_FIELD_NUMBER = 1;
  private int pageNumber_;
  /**
   * <code>int32 pageNumber = 1;</code>
   * @return The pageNumber.
   */
  public int getPageNumber() {
    return pageNumber_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pageSize_;
  /**
   * <code>int32 pageSize = 2;</code>
   * @return The pageSize.
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int OFFSET_FIELD_NUMBER = 3;
  private long offset_;
  /**
   * <code>int64 offset = 3;</code>
   * @return The offset.
   */
  public long getOffset() {
    return offset_;
  }

  public static final int PAGED_FIELD_NUMBER = 4;
  private boolean paged_;
  /**
   * <code>bool paged = 4;</code>
   * @return The paged.
   */
  public boolean getPaged() {
    return paged_;
  }

  public static final int UNPAGED_FIELD_NUMBER = 5;
  private boolean unpaged_;
  /**
   * <code>bool unpaged = 5;</code>
   * @return The unpaged.
   */
  public boolean getUnpaged() {
    return unpaged_;
  }

  public static final int SORT_FIELD_NUMBER = 6;
  private org.devolpex.backend.stubs.shared.SortPRT sort_;
  /**
   * <code>.SortPRT sort = 6;</code>
   * @return Whether the sort field is set.
   */
  public boolean hasSort() {
    return sort_ != null;
  }
  /**
   * <code>.SortPRT sort = 6;</code>
   * @return The sort.
   */
  public org.devolpex.backend.stubs.shared.SortPRT getSort() {
    return sort_ == null ? org.devolpex.backend.stubs.shared.SortPRT.getDefaultInstance() : sort_;
  }
  /**
   * <code>.SortPRT sort = 6;</code>
   */
  public org.devolpex.backend.stubs.shared.SortPRTOrBuilder getSortOrBuilder() {
    return getSort();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageNumber_ != 0) {
      output.writeInt32(1, pageNumber_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(2, pageSize_);
    }
    if (offset_ != 0L) {
      output.writeInt64(3, offset_);
    }
    if (paged_ != false) {
      output.writeBool(4, paged_);
    }
    if (unpaged_ != false) {
      output.writeBool(5, unpaged_);
    }
    if (sort_ != null) {
      output.writeMessage(6, getSort());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pageNumber_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageSize_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, offset_);
    }
    if (paged_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, paged_);
    }
    if (unpaged_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, unpaged_);
    }
    if (sort_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getSort());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.devolpex.backend.stubs.shared.PageablePRT)) {
      return super.equals(obj);
    }
    org.devolpex.backend.stubs.shared.PageablePRT other = (org.devolpex.backend.stubs.shared.PageablePRT) obj;

    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (getPaged()
        != other.getPaged()) return false;
    if (getUnpaged()
        != other.getUnpaged()) return false;
    if (hasSort() != other.hasSort()) return false;
    if (hasSort()) {
      if (!getSort()
          .equals(other.getSort())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPageNumber();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + PAGED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPaged());
    hash = (37 * hash) + UNPAGED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUnpaged());
    if (hasSort()) {
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + getSort().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.PageablePRT parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.devolpex.backend.stubs.shared.PageablePRT prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Pageable message definition
   * </pre>
   *
   * Protobuf type {@code PageablePRT}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PageablePRT)
      org.devolpex.backend.stubs.shared.PageablePRTOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_PageablePRT_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_PageablePRT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.devolpex.backend.stubs.shared.PageablePRT.class, org.devolpex.backend.stubs.shared.PageablePRT.Builder.class);
    }

    // Construct using org.devolpex.backend.stubs.shared.PageablePRT.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pageNumber_ = 0;

      pageSize_ = 0;

      offset_ = 0L;

      paged_ = false;

      unpaged_ = false;

      if (sortBuilder_ == null) {
        sort_ = null;
      } else {
        sort_ = null;
        sortBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_PageablePRT_descriptor;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.PageablePRT getDefaultInstanceForType() {
      return org.devolpex.backend.stubs.shared.PageablePRT.getDefaultInstance();
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.PageablePRT build() {
      org.devolpex.backend.stubs.shared.PageablePRT result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.PageablePRT buildPartial() {
      org.devolpex.backend.stubs.shared.PageablePRT result = new org.devolpex.backend.stubs.shared.PageablePRT(this);
      result.pageNumber_ = pageNumber_;
      result.pageSize_ = pageSize_;
      result.offset_ = offset_;
      result.paged_ = paged_;
      result.unpaged_ = unpaged_;
      if (sortBuilder_ == null) {
        result.sort_ = sort_;
      } else {
        result.sort_ = sortBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.devolpex.backend.stubs.shared.PageablePRT) {
        return mergeFrom((org.devolpex.backend.stubs.shared.PageablePRT)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.devolpex.backend.stubs.shared.PageablePRT other) {
      if (other == org.devolpex.backend.stubs.shared.PageablePRT.getDefaultInstance()) return this;
      if (other.getPageNumber() != 0) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (other.getPaged() != false) {
        setPaged(other.getPaged());
      }
      if (other.getUnpaged() != false) {
        setUnpaged(other.getUnpaged());
      }
      if (other.hasSort()) {
        mergeSort(other.getSort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.devolpex.backend.stubs.shared.PageablePRT parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.devolpex.backend.stubs.shared.PageablePRT) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pageNumber_ ;
    /**
     * <code>int32 pageNumber = 1;</code>
     * @return The pageNumber.
     */
    public int getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>int32 pageNumber = 1;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(int value) {
      
      pageNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      
      pageNumber_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 pageSize = 2;</code>
     * @return The pageSize.
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pageSize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>int64 offset = 3;</code>
     * @return The offset.
     */
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 3;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0L;
      onChanged();
      return this;
    }

    private boolean paged_ ;
    /**
     * <code>bool paged = 4;</code>
     * @return The paged.
     */
    public boolean getPaged() {
      return paged_;
    }
    /**
     * <code>bool paged = 4;</code>
     * @param value The paged to set.
     * @return This builder for chaining.
     */
    public Builder setPaged(boolean value) {
      
      paged_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool paged = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaged() {
      
      paged_ = false;
      onChanged();
      return this;
    }

    private boolean unpaged_ ;
    /**
     * <code>bool unpaged = 5;</code>
     * @return The unpaged.
     */
    public boolean getUnpaged() {
      return unpaged_;
    }
    /**
     * <code>bool unpaged = 5;</code>
     * @param value The unpaged to set.
     * @return This builder for chaining.
     */
    public Builder setUnpaged(boolean value) {
      
      unpaged_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool unpaged = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnpaged() {
      
      unpaged_ = false;
      onChanged();
      return this;
    }

    private org.devolpex.backend.stubs.shared.SortPRT sort_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.shared.SortPRT, org.devolpex.backend.stubs.shared.SortPRT.Builder, org.devolpex.backend.stubs.shared.SortPRTOrBuilder> sortBuilder_;
    /**
     * <code>.SortPRT sort = 6;</code>
     * @return Whether the sort field is set.
     */
    public boolean hasSort() {
      return sortBuilder_ != null || sort_ != null;
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     * @return The sort.
     */
    public org.devolpex.backend.stubs.shared.SortPRT getSort() {
      if (sortBuilder_ == null) {
        return sort_ == null ? org.devolpex.backend.stubs.shared.SortPRT.getDefaultInstance() : sort_;
      } else {
        return sortBuilder_.getMessage();
      }
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public Builder setSort(org.devolpex.backend.stubs.shared.SortPRT value) {
      if (sortBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sort_ = value;
        onChanged();
      } else {
        sortBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public Builder setSort(
        org.devolpex.backend.stubs.shared.SortPRT.Builder builderForValue) {
      if (sortBuilder_ == null) {
        sort_ = builderForValue.build();
        onChanged();
      } else {
        sortBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public Builder mergeSort(org.devolpex.backend.stubs.shared.SortPRT value) {
      if (sortBuilder_ == null) {
        if (sort_ != null) {
          sort_ =
            org.devolpex.backend.stubs.shared.SortPRT.newBuilder(sort_).mergeFrom(value).buildPartial();
        } else {
          sort_ = value;
        }
        onChanged();
      } else {
        sortBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public Builder clearSort() {
      if (sortBuilder_ == null) {
        sort_ = null;
        onChanged();
      } else {
        sort_ = null;
        sortBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public org.devolpex.backend.stubs.shared.SortPRT.Builder getSortBuilder() {
      
      onChanged();
      return getSortFieldBuilder().getBuilder();
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    public org.devolpex.backend.stubs.shared.SortPRTOrBuilder getSortOrBuilder() {
      if (sortBuilder_ != null) {
        return sortBuilder_.getMessageOrBuilder();
      } else {
        return sort_ == null ?
            org.devolpex.backend.stubs.shared.SortPRT.getDefaultInstance() : sort_;
      }
    }
    /**
     * <code>.SortPRT sort = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.shared.SortPRT, org.devolpex.backend.stubs.shared.SortPRT.Builder, org.devolpex.backend.stubs.shared.SortPRTOrBuilder> 
        getSortFieldBuilder() {
      if (sortBuilder_ == null) {
        sortBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.devolpex.backend.stubs.shared.SortPRT, org.devolpex.backend.stubs.shared.SortPRT.Builder, org.devolpex.backend.stubs.shared.SortPRTOrBuilder>(
                getSort(),
                getParentForChildren(),
                isClean());
        sort_ = null;
      }
      return sortBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PageablePRT)
  }

  // @@protoc_insertion_point(class_scope:PageablePRT)
  private static final org.devolpex.backend.stubs.shared.PageablePRT DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.devolpex.backend.stubs.shared.PageablePRT();
  }

  public static org.devolpex.backend.stubs.shared.PageablePRT getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PageablePRT>
      PARSER = new com.google.protobuf.AbstractParser<PageablePRT>() {
    @java.lang.Override
    public PageablePRT parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PageablePRT(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PageablePRT> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PageablePRT> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.devolpex.backend.stubs.shared.PageablePRT getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

