// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package org.devolpex.backend.stubs.shared;

public final class Shared {
  private Shared() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageablePRT_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageablePRT_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SortPRT_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SortPRT_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014shared.proto\"{\n\013PageablePRT\022\022\n\npageNum" +
      "ber\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\016\n\006offset\030\003 " +
      "\001(\003\022\r\n\005paged\030\004 \001(\010\022\017\n\007unpaged\030\005 \001(\010\022\026\n\004s" +
      "ort\030\006 \001(\0132\010.SortPRT\":\n\007SortPRT\022\016\n\006sorted" +
      "\030\001 \001(\010\022\020\n\010unsorted\030\002 \001(\010\022\r\n\005empty\030\003 \001(\010B" +
      "%\n!org.devolpex.backend.stubs.sharedP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PageablePRT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PageablePRT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageablePRT_descriptor,
        new java.lang.String[] { "PageNumber", "PageSize", "Offset", "Paged", "Unpaged", "Sort", });
    internal_static_SortPRT_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SortPRT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SortPRT_descriptor,
        new java.lang.String[] { "Sorted", "Unsorted", "Empty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
