// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared.proto

package org.devolpex.backend.stubs.shared;

/**
 * <pre>
 * Sort message definition
 * </pre>
 *
 * Protobuf type {@code SortPRT}
 */
public  final class SortPRT extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SortPRT)
    SortPRTOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SortPRT.newBuilder() to construct.
  private SortPRT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SortPRT() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SortPRT();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SortPRT(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sorted_ = input.readBool();
            break;
          }
          case 16: {

            unsorted_ = input.readBool();
            break;
          }
          case 24: {

            empty_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.devolpex.backend.stubs.shared.Shared.internal_static_SortPRT_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.devolpex.backend.stubs.shared.Shared.internal_static_SortPRT_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.devolpex.backend.stubs.shared.SortPRT.class, org.devolpex.backend.stubs.shared.SortPRT.Builder.class);
  }

  public static final int SORTED_FIELD_NUMBER = 1;
  private boolean sorted_;
  /**
   * <code>bool sorted = 1;</code>
   * @return The sorted.
   */
  public boolean getSorted() {
    return sorted_;
  }

  public static final int UNSORTED_FIELD_NUMBER = 2;
  private boolean unsorted_;
  /**
   * <code>bool unsorted = 2;</code>
   * @return The unsorted.
   */
  public boolean getUnsorted() {
    return unsorted_;
  }

  public static final int EMPTY_FIELD_NUMBER = 3;
  private boolean empty_;
  /**
   * <code>bool empty = 3;</code>
   * @return The empty.
   */
  public boolean getEmpty() {
    return empty_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sorted_ != false) {
      output.writeBool(1, sorted_);
    }
    if (unsorted_ != false) {
      output.writeBool(2, unsorted_);
    }
    if (empty_ != false) {
      output.writeBool(3, empty_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sorted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, sorted_);
    }
    if (unsorted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, unsorted_);
    }
    if (empty_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, empty_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.devolpex.backend.stubs.shared.SortPRT)) {
      return super.equals(obj);
    }
    org.devolpex.backend.stubs.shared.SortPRT other = (org.devolpex.backend.stubs.shared.SortPRT) obj;

    if (getSorted()
        != other.getSorted()) return false;
    if (getUnsorted()
        != other.getUnsorted()) return false;
    if (getEmpty()
        != other.getEmpty()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SORTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSorted());
    hash = (37 * hash) + UNSORTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUnsorted());
    hash = (37 * hash) + EMPTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEmpty());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.shared.SortPRT parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.devolpex.backend.stubs.shared.SortPRT prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Sort message definition
   * </pre>
   *
   * Protobuf type {@code SortPRT}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SortPRT)
      org.devolpex.backend.stubs.shared.SortPRTOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_SortPRT_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_SortPRT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.devolpex.backend.stubs.shared.SortPRT.class, org.devolpex.backend.stubs.shared.SortPRT.Builder.class);
    }

    // Construct using org.devolpex.backend.stubs.shared.SortPRT.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sorted_ = false;

      unsorted_ = false;

      empty_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.devolpex.backend.stubs.shared.Shared.internal_static_SortPRT_descriptor;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.SortPRT getDefaultInstanceForType() {
      return org.devolpex.backend.stubs.shared.SortPRT.getDefaultInstance();
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.SortPRT build() {
      org.devolpex.backend.stubs.shared.SortPRT result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.shared.SortPRT buildPartial() {
      org.devolpex.backend.stubs.shared.SortPRT result = new org.devolpex.backend.stubs.shared.SortPRT(this);
      result.sorted_ = sorted_;
      result.unsorted_ = unsorted_;
      result.empty_ = empty_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.devolpex.backend.stubs.shared.SortPRT) {
        return mergeFrom((org.devolpex.backend.stubs.shared.SortPRT)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.devolpex.backend.stubs.shared.SortPRT other) {
      if (other == org.devolpex.backend.stubs.shared.SortPRT.getDefaultInstance()) return this;
      if (other.getSorted() != false) {
        setSorted(other.getSorted());
      }
      if (other.getUnsorted() != false) {
        setUnsorted(other.getUnsorted());
      }
      if (other.getEmpty() != false) {
        setEmpty(other.getEmpty());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.devolpex.backend.stubs.shared.SortPRT parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.devolpex.backend.stubs.shared.SortPRT) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean sorted_ ;
    /**
     * <code>bool sorted = 1;</code>
     * @return The sorted.
     */
    public boolean getSorted() {
      return sorted_;
    }
    /**
     * <code>bool sorted = 1;</code>
     * @param value The sorted to set.
     * @return This builder for chaining.
     */
    public Builder setSorted(boolean value) {
      
      sorted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool sorted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSorted() {
      
      sorted_ = false;
      onChanged();
      return this;
    }

    private boolean unsorted_ ;
    /**
     * <code>bool unsorted = 2;</code>
     * @return The unsorted.
     */
    public boolean getUnsorted() {
      return unsorted_;
    }
    /**
     * <code>bool unsorted = 2;</code>
     * @param value The unsorted to set.
     * @return This builder for chaining.
     */
    public Builder setUnsorted(boolean value) {
      
      unsorted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool unsorted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnsorted() {
      
      unsorted_ = false;
      onChanged();
      return this;
    }

    private boolean empty_ ;
    /**
     * <code>bool empty = 3;</code>
     * @return The empty.
     */
    public boolean getEmpty() {
      return empty_;
    }
    /**
     * <code>bool empty = 3;</code>
     * @param value The empty to set.
     * @return This builder for chaining.
     */
    public Builder setEmpty(boolean value) {
      
      empty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool empty = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmpty() {
      
      empty_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SortPRT)
  }

  // @@protoc_insertion_point(class_scope:SortPRT)
  private static final org.devolpex.backend.stubs.shared.SortPRT DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.devolpex.backend.stubs.shared.SortPRT();
  }

  public static org.devolpex.backend.stubs.shared.SortPRT getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SortPRT>
      PARSER = new com.google.protobuf.AbstractParser<SortPRT>() {
    @java.lang.Override
    public SortPRT parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SortPRT(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SortPRT> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SortPRT> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.devolpex.backend.stubs.shared.SortPRT getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

