// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface ClientPagePRTOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientPagePRT)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  java.util.List<org.devolpex.backend.stubs.client.ClientPRT> 
      getContentList();
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPRT getContent(int index);
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  int getContentCount();
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  java.util.List<? extends org.devolpex.backend.stubs.client.ClientPRTOrBuilder> 
      getContentOrBuilderList();
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPRTOrBuilder getContentOrBuilder(
      int index);

  /**
   * <code>.PageablePRT pageable = 2;</code>
   * @return Whether the pageable field is set.
   */
  boolean hasPageable();
  /**
   * <code>.PageablePRT pageable = 2;</code>
   * @return The pageable.
   */
  org.devolpex.backend.stubs.shared.PageablePRT getPageable();
  /**
   * <code>.PageablePRT pageable = 2;</code>
   */
  org.devolpex.backend.stubs.shared.PageablePRTOrBuilder getPageableOrBuilder();

  /**
   * <code>int64 totalElements = 3;</code>
   * @return The totalElements.
   */
  long getTotalElements();

  /**
   * <code>int32 totalPages = 4;</code>
   * @return The totalPages.
   */
  int getTotalPages();

  /**
   * <code>bool last = 5;</code>
   * @return The last.
   */
  boolean getLast();

  /**
   * <code>bool first = 6;</code>
   * @return The first.
   */
  boolean getFirst();

  /**
   * <code>int32 size = 7;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>int32 number = 8;</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>int32 numberOfElements = 9;</code>
   * @return The numberOfElements.
   */
  int getNumberOfElements();

  /**
   * <code>bool empty = 10;</code>
   * @return The empty.
   */
  boolean getEmpty();
}
