// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface ClientPRTOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientPRT)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string nom = 2;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string prenom = 3;</code>
   * @return The prenom.
   */
  java.lang.String getPrenom();
  /**
   * <code>string prenom = 3;</code>
   * @return The bytes for prenom.
   */
  com.google.protobuf.ByteString
      getPrenomBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string telephone = 5;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>string telephone = 5;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();

  /**
   * <code>repeated .ReservationPRT reservations = 6;</code>
   */
  java.util.List<org.devolpex.backend.stubs.client.ReservationPRT> 
      getReservationsList();
  /**
   * <code>repeated .ReservationPRT reservations = 6;</code>
   */
  org.devolpex.backend.stubs.client.ReservationPRT getReservations(int index);
  /**
   * <code>repeated .ReservationPRT reservations = 6;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .ReservationPRT reservations = 6;</code>
   */
  java.util.List<? extends org.devolpex.backend.stubs.client.ReservationPRTOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .ReservationPRT reservations = 6;</code>
   */
  org.devolpex.backend.stubs.client.ReservationPRTOrBuilder getReservationsOrBuilder(
      int index);
}
