// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

/**
 * Protobuf type {@code ClientPagePRT}
 */
public  final class ClientPagePRT extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientPagePRT)
    ClientPagePRTOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientPagePRT.newBuilder() to construct.
  private ClientPagePRT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientPagePRT() {
    content_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientPagePRT();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientPagePRT(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              content_ = new java.util.ArrayList<org.devolpex.backend.stubs.client.ClientPRT>();
              mutable_bitField0_ |= 0x00000001;
            }
            content_.add(
                input.readMessage(org.devolpex.backend.stubs.client.ClientPRT.parser(), extensionRegistry));
            break;
          }
          case 18: {
            org.devolpex.backend.stubs.shared.PageablePRT.Builder subBuilder = null;
            if (pageable_ != null) {
              subBuilder = pageable_.toBuilder();
            }
            pageable_ = input.readMessage(org.devolpex.backend.stubs.shared.PageablePRT.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageable_);
              pageable_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            totalElements_ = input.readInt64();
            break;
          }
          case 32: {

            totalPages_ = input.readInt32();
            break;
          }
          case 40: {

            last_ = input.readBool();
            break;
          }
          case 48: {

            first_ = input.readBool();
            break;
          }
          case 56: {

            size_ = input.readInt32();
            break;
          }
          case 64: {

            number_ = input.readInt32();
            break;
          }
          case 72: {

            numberOfElements_ = input.readInt32();
            break;
          }
          case 80: {

            empty_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        content_ = java.util.Collections.unmodifiableList(content_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.devolpex.backend.stubs.client.ClientOuterClass.internal_static_ClientPagePRT_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.devolpex.backend.stubs.client.ClientOuterClass.internal_static_ClientPagePRT_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.devolpex.backend.stubs.client.ClientPagePRT.class, org.devolpex.backend.stubs.client.ClientPagePRT.Builder.class);
  }

  public static final int CONTENT_FIELD_NUMBER = 1;
  private java.util.List<org.devolpex.backend.stubs.client.ClientPRT> content_;
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  public java.util.List<org.devolpex.backend.stubs.client.ClientPRT> getContentList() {
    return content_;
  }
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  public java.util.List<? extends org.devolpex.backend.stubs.client.ClientPRTOrBuilder> 
      getContentOrBuilderList() {
    return content_;
  }
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  public int getContentCount() {
    return content_.size();
  }
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  public org.devolpex.backend.stubs.client.ClientPRT getContent(int index) {
    return content_.get(index);
  }
  /**
   * <code>repeated .ClientPRT content = 1;</code>
   */
  public org.devolpex.backend.stubs.client.ClientPRTOrBuilder getContentOrBuilder(
      int index) {
    return content_.get(index);
  }

  public static final int PAGEABLE_FIELD_NUMBER = 2;
  private org.devolpex.backend.stubs.shared.PageablePRT pageable_;
  /**
   * <code>.PageablePRT pageable = 2;</code>
   * @return Whether the pageable field is set.
   */
  public boolean hasPageable() {
    return pageable_ != null;
  }
  /**
   * <code>.PageablePRT pageable = 2;</code>
   * @return The pageable.
   */
  public org.devolpex.backend.stubs.shared.PageablePRT getPageable() {
    return pageable_ == null ? org.devolpex.backend.stubs.shared.PageablePRT.getDefaultInstance() : pageable_;
  }
  /**
   * <code>.PageablePRT pageable = 2;</code>
   */
  public org.devolpex.backend.stubs.shared.PageablePRTOrBuilder getPageableOrBuilder() {
    return getPageable();
  }

  public static final int TOTALELEMENTS_FIELD_NUMBER = 3;
  private long totalElements_;
  /**
   * <code>int64 totalElements = 3;</code>
   * @return The totalElements.
   */
  public long getTotalElements() {
    return totalElements_;
  }

  public static final int TOTALPAGES_FIELD_NUMBER = 4;
  private int totalPages_;
  /**
   * <code>int32 totalPages = 4;</code>
   * @return The totalPages.
   */
  public int getTotalPages() {
    return totalPages_;
  }

  public static final int LAST_FIELD_NUMBER = 5;
  private boolean last_;
  /**
   * <code>bool last = 5;</code>
   * @return The last.
   */
  public boolean getLast() {
    return last_;
  }

  public static final int FIRST_FIELD_NUMBER = 6;
  private boolean first_;
  /**
   * <code>bool first = 6;</code>
   * @return The first.
   */
  public boolean getFirst() {
    return first_;
  }

  public static final int SIZE_FIELD_NUMBER = 7;
  private int size_;
  /**
   * <code>int32 size = 7;</code>
   * @return The size.
   */
  public int getSize() {
    return size_;
  }

  public static final int NUMBER_FIELD_NUMBER = 8;
  private int number_;
  /**
   * <code>int32 number = 8;</code>
   * @return The number.
   */
  public int getNumber() {
    return number_;
  }

  public static final int NUMBEROFELEMENTS_FIELD_NUMBER = 9;
  private int numberOfElements_;
  /**
   * <code>int32 numberOfElements = 9;</code>
   * @return The numberOfElements.
   */
  public int getNumberOfElements() {
    return numberOfElements_;
  }

  public static final int EMPTY_FIELD_NUMBER = 10;
  private boolean empty_;
  /**
   * <code>bool empty = 10;</code>
   * @return The empty.
   */
  public boolean getEmpty() {
    return empty_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < content_.size(); i++) {
      output.writeMessage(1, content_.get(i));
    }
    if (pageable_ != null) {
      output.writeMessage(2, getPageable());
    }
    if (totalElements_ != 0L) {
      output.writeInt64(3, totalElements_);
    }
    if (totalPages_ != 0) {
      output.writeInt32(4, totalPages_);
    }
    if (last_ != false) {
      output.writeBool(5, last_);
    }
    if (first_ != false) {
      output.writeBool(6, first_);
    }
    if (size_ != 0) {
      output.writeInt32(7, size_);
    }
    if (number_ != 0) {
      output.writeInt32(8, number_);
    }
    if (numberOfElements_ != 0) {
      output.writeInt32(9, numberOfElements_);
    }
    if (empty_ != false) {
      output.writeBool(10, empty_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < content_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, content_.get(i));
    }
    if (pageable_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPageable());
    }
    if (totalElements_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, totalElements_);
    }
    if (totalPages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalPages_);
    }
    if (last_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, last_);
    }
    if (first_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, first_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, size_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, number_);
    }
    if (numberOfElements_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, numberOfElements_);
    }
    if (empty_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, empty_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.devolpex.backend.stubs.client.ClientPagePRT)) {
      return super.equals(obj);
    }
    org.devolpex.backend.stubs.client.ClientPagePRT other = (org.devolpex.backend.stubs.client.ClientPagePRT) obj;

    if (!getContentList()
        .equals(other.getContentList())) return false;
    if (hasPageable() != other.hasPageable()) return false;
    if (hasPageable()) {
      if (!getPageable()
          .equals(other.getPageable())) return false;
    }
    if (getTotalElements()
        != other.getTotalElements()) return false;
    if (getTotalPages()
        != other.getTotalPages()) return false;
    if (getLast()
        != other.getLast()) return false;
    if (getFirst()
        != other.getFirst()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (getNumber()
        != other.getNumber()) return false;
    if (getNumberOfElements()
        != other.getNumberOfElements()) return false;
    if (getEmpty()
        != other.getEmpty()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContentCount() > 0) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContentList().hashCode();
    }
    if (hasPageable()) {
      hash = (37 * hash) + PAGEABLE_FIELD_NUMBER;
      hash = (53 * hash) + getPageable().hashCode();
    }
    hash = (37 * hash) + TOTALELEMENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalElements());
    hash = (37 * hash) + TOTALPAGES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPages();
    hash = (37 * hash) + LAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLast());
    hash = (37 * hash) + FIRST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFirst());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (37 * hash) + NUMBEROFELEMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfElements();
    hash = (37 * hash) + EMPTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEmpty());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.client.ClientPagePRT parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.devolpex.backend.stubs.client.ClientPagePRT prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientPagePRT}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientPagePRT)
      org.devolpex.backend.stubs.client.ClientPagePRTOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devolpex.backend.stubs.client.ClientOuterClass.internal_static_ClientPagePRT_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devolpex.backend.stubs.client.ClientOuterClass.internal_static_ClientPagePRT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.devolpex.backend.stubs.client.ClientPagePRT.class, org.devolpex.backend.stubs.client.ClientPagePRT.Builder.class);
    }

    // Construct using org.devolpex.backend.stubs.client.ClientPagePRT.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getContentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contentBuilder_ == null) {
        content_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        contentBuilder_.clear();
      }
      if (pageableBuilder_ == null) {
        pageable_ = null;
      } else {
        pageable_ = null;
        pageableBuilder_ = null;
      }
      totalElements_ = 0L;

      totalPages_ = 0;

      last_ = false;

      first_ = false;

      size_ = 0;

      number_ = 0;

      numberOfElements_ = 0;

      empty_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.devolpex.backend.stubs.client.ClientOuterClass.internal_static_ClientPagePRT_descriptor;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.client.ClientPagePRT getDefaultInstanceForType() {
      return org.devolpex.backend.stubs.client.ClientPagePRT.getDefaultInstance();
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.client.ClientPagePRT build() {
      org.devolpex.backend.stubs.client.ClientPagePRT result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.client.ClientPagePRT buildPartial() {
      org.devolpex.backend.stubs.client.ClientPagePRT result = new org.devolpex.backend.stubs.client.ClientPagePRT(this);
      int from_bitField0_ = bitField0_;
      if (contentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          content_ = java.util.Collections.unmodifiableList(content_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.content_ = content_;
      } else {
        result.content_ = contentBuilder_.build();
      }
      if (pageableBuilder_ == null) {
        result.pageable_ = pageable_;
      } else {
        result.pageable_ = pageableBuilder_.build();
      }
      result.totalElements_ = totalElements_;
      result.totalPages_ = totalPages_;
      result.last_ = last_;
      result.first_ = first_;
      result.size_ = size_;
      result.number_ = number_;
      result.numberOfElements_ = numberOfElements_;
      result.empty_ = empty_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.devolpex.backend.stubs.client.ClientPagePRT) {
        return mergeFrom((org.devolpex.backend.stubs.client.ClientPagePRT)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.devolpex.backend.stubs.client.ClientPagePRT other) {
      if (other == org.devolpex.backend.stubs.client.ClientPagePRT.getDefaultInstance()) return this;
      if (contentBuilder_ == null) {
        if (!other.content_.isEmpty()) {
          if (content_.isEmpty()) {
            content_ = other.content_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContentIsMutable();
            content_.addAll(other.content_);
          }
          onChanged();
        }
      } else {
        if (!other.content_.isEmpty()) {
          if (contentBuilder_.isEmpty()) {
            contentBuilder_.dispose();
            contentBuilder_ = null;
            content_ = other.content_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContentFieldBuilder() : null;
          } else {
            contentBuilder_.addAllMessages(other.content_);
          }
        }
      }
      if (other.hasPageable()) {
        mergePageable(other.getPageable());
      }
      if (other.getTotalElements() != 0L) {
        setTotalElements(other.getTotalElements());
      }
      if (other.getTotalPages() != 0) {
        setTotalPages(other.getTotalPages());
      }
      if (other.getLast() != false) {
        setLast(other.getLast());
      }
      if (other.getFirst() != false) {
        setFirst(other.getFirst());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      if (other.getNumberOfElements() != 0) {
        setNumberOfElements(other.getNumberOfElements());
      }
      if (other.getEmpty() != false) {
        setEmpty(other.getEmpty());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.devolpex.backend.stubs.client.ClientPagePRT parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.devolpex.backend.stubs.client.ClientPagePRT) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.devolpex.backend.stubs.client.ClientPRT> content_ =
      java.util.Collections.emptyList();
    private void ensureContentIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        content_ = new java.util.ArrayList<org.devolpex.backend.stubs.client.ClientPRT>(content_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.devolpex.backend.stubs.client.ClientPRT, org.devolpex.backend.stubs.client.ClientPRT.Builder, org.devolpex.backend.stubs.client.ClientPRTOrBuilder> contentBuilder_;

    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public java.util.List<org.devolpex.backend.stubs.client.ClientPRT> getContentList() {
      if (contentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(content_);
      } else {
        return contentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public int getContentCount() {
      if (contentBuilder_ == null) {
        return content_.size();
      } else {
        return contentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientPRT getContent(int index) {
      if (contentBuilder_ == null) {
        return content_.get(index);
      } else {
        return contentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder setContent(
        int index, org.devolpex.backend.stubs.client.ClientPRT value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.set(index, value);
        onChanged();
      } else {
        contentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder setContent(
        int index, org.devolpex.backend.stubs.client.ClientPRT.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder addContent(org.devolpex.backend.stubs.client.ClientPRT value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.add(value);
        onChanged();
      } else {
        contentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder addContent(
        int index, org.devolpex.backend.stubs.client.ClientPRT value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.add(index, value);
        onChanged();
      } else {
        contentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder addContent(
        org.devolpex.backend.stubs.client.ClientPRT.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.add(builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder addContent(
        int index, org.devolpex.backend.stubs.client.ClientPRT.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder addAllContent(
        java.lang.Iterable<? extends org.devolpex.backend.stubs.client.ClientPRT> values) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, content_);
        onChanged();
      } else {
        contentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder clearContent() {
      if (contentBuilder_ == null) {
        content_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public Builder removeContent(int index) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.remove(index);
        onChanged();
      } else {
        contentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientPRT.Builder getContentBuilder(
        int index) {
      return getContentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientPRTOrBuilder getContentOrBuilder(
        int index) {
      if (contentBuilder_ == null) {
        return content_.get(index);  } else {
        return contentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public java.util.List<? extends org.devolpex.backend.stubs.client.ClientPRTOrBuilder> 
         getContentOrBuilderList() {
      if (contentBuilder_ != null) {
        return contentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(content_);
      }
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientPRT.Builder addContentBuilder() {
      return getContentFieldBuilder().addBuilder(
          org.devolpex.backend.stubs.client.ClientPRT.getDefaultInstance());
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientPRT.Builder addContentBuilder(
        int index) {
      return getContentFieldBuilder().addBuilder(
          index, org.devolpex.backend.stubs.client.ClientPRT.getDefaultInstance());
    }
    /**
     * <code>repeated .ClientPRT content = 1;</code>
     */
    public java.util.List<org.devolpex.backend.stubs.client.ClientPRT.Builder> 
         getContentBuilderList() {
      return getContentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.devolpex.backend.stubs.client.ClientPRT, org.devolpex.backend.stubs.client.ClientPRT.Builder, org.devolpex.backend.stubs.client.ClientPRTOrBuilder> 
        getContentFieldBuilder() {
      if (contentBuilder_ == null) {
        contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.devolpex.backend.stubs.client.ClientPRT, org.devolpex.backend.stubs.client.ClientPRT.Builder, org.devolpex.backend.stubs.client.ClientPRTOrBuilder>(
                content_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      return contentBuilder_;
    }

    private org.devolpex.backend.stubs.shared.PageablePRT pageable_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.shared.PageablePRT, org.devolpex.backend.stubs.shared.PageablePRT.Builder, org.devolpex.backend.stubs.shared.PageablePRTOrBuilder> pageableBuilder_;
    /**
     * <code>.PageablePRT pageable = 2;</code>
     * @return Whether the pageable field is set.
     */
    public boolean hasPageable() {
      return pageableBuilder_ != null || pageable_ != null;
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     * @return The pageable.
     */
    public org.devolpex.backend.stubs.shared.PageablePRT getPageable() {
      if (pageableBuilder_ == null) {
        return pageable_ == null ? org.devolpex.backend.stubs.shared.PageablePRT.getDefaultInstance() : pageable_;
      } else {
        return pageableBuilder_.getMessage();
      }
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public Builder setPageable(org.devolpex.backend.stubs.shared.PageablePRT value) {
      if (pageableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageable_ = value;
        onChanged();
      } else {
        pageableBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public Builder setPageable(
        org.devolpex.backend.stubs.shared.PageablePRT.Builder builderForValue) {
      if (pageableBuilder_ == null) {
        pageable_ = builderForValue.build();
        onChanged();
      } else {
        pageableBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public Builder mergePageable(org.devolpex.backend.stubs.shared.PageablePRT value) {
      if (pageableBuilder_ == null) {
        if (pageable_ != null) {
          pageable_ =
            org.devolpex.backend.stubs.shared.PageablePRT.newBuilder(pageable_).mergeFrom(value).buildPartial();
        } else {
          pageable_ = value;
        }
        onChanged();
      } else {
        pageableBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public Builder clearPageable() {
      if (pageableBuilder_ == null) {
        pageable_ = null;
        onChanged();
      } else {
        pageable_ = null;
        pageableBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public org.devolpex.backend.stubs.shared.PageablePRT.Builder getPageableBuilder() {
      
      onChanged();
      return getPageableFieldBuilder().getBuilder();
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    public org.devolpex.backend.stubs.shared.PageablePRTOrBuilder getPageableOrBuilder() {
      if (pageableBuilder_ != null) {
        return pageableBuilder_.getMessageOrBuilder();
      } else {
        return pageable_ == null ?
            org.devolpex.backend.stubs.shared.PageablePRT.getDefaultInstance() : pageable_;
      }
    }
    /**
     * <code>.PageablePRT pageable = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.shared.PageablePRT, org.devolpex.backend.stubs.shared.PageablePRT.Builder, org.devolpex.backend.stubs.shared.PageablePRTOrBuilder> 
        getPageableFieldBuilder() {
      if (pageableBuilder_ == null) {
        pageableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.devolpex.backend.stubs.shared.PageablePRT, org.devolpex.backend.stubs.shared.PageablePRT.Builder, org.devolpex.backend.stubs.shared.PageablePRTOrBuilder>(
                getPageable(),
                getParentForChildren(),
                isClean());
        pageable_ = null;
      }
      return pageableBuilder_;
    }

    private long totalElements_ ;
    /**
     * <code>int64 totalElements = 3;</code>
     * @return The totalElements.
     */
    public long getTotalElements() {
      return totalElements_;
    }
    /**
     * <code>int64 totalElements = 3;</code>
     * @param value The totalElements to set.
     * @return This builder for chaining.
     */
    public Builder setTotalElements(long value) {
      
      totalElements_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalElements = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalElements() {
      
      totalElements_ = 0L;
      onChanged();
      return this;
    }

    private int totalPages_ ;
    /**
     * <code>int32 totalPages = 4;</code>
     * @return The totalPages.
     */
    public int getTotalPages() {
      return totalPages_;
    }
    /**
     * <code>int32 totalPages = 4;</code>
     * @param value The totalPages to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPages(int value) {
      
      totalPages_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalPages = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPages() {
      
      totalPages_ = 0;
      onChanged();
      return this;
    }

    private boolean last_ ;
    /**
     * <code>bool last = 5;</code>
     * @return The last.
     */
    public boolean getLast() {
      return last_;
    }
    /**
     * <code>bool last = 5;</code>
     * @param value The last to set.
     * @return This builder for chaining.
     */
    public Builder setLast(boolean value) {
      
      last_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool last = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLast() {
      
      last_ = false;
      onChanged();
      return this;
    }

    private boolean first_ ;
    /**
     * <code>bool first = 6;</code>
     * @return The first.
     */
    public boolean getFirst() {
      return first_;
    }
    /**
     * <code>bool first = 6;</code>
     * @param value The first to set.
     * @return This builder for chaining.
     */
    public Builder setFirst(boolean value) {
      
      first_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool first = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirst() {
      
      first_ = false;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 7;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 7;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }

    private int number_ ;
    /**
     * <code>int32 number = 8;</code>
     * @return The number.
     */
    public int getNumber() {
      return number_;
    }
    /**
     * <code>int32 number = 8;</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(int value) {
      
      number_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      
      number_ = 0;
      onChanged();
      return this;
    }

    private int numberOfElements_ ;
    /**
     * <code>int32 numberOfElements = 9;</code>
     * @return The numberOfElements.
     */
    public int getNumberOfElements() {
      return numberOfElements_;
    }
    /**
     * <code>int32 numberOfElements = 9;</code>
     * @param value The numberOfElements to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfElements(int value) {
      
      numberOfElements_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfElements = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfElements() {
      
      numberOfElements_ = 0;
      onChanged();
      return this;
    }

    private boolean empty_ ;
    /**
     * <code>bool empty = 10;</code>
     * @return The empty.
     */
    public boolean getEmpty() {
      return empty_;
    }
    /**
     * <code>bool empty = 10;</code>
     * @param value The empty to set.
     * @return This builder for chaining.
     */
    public Builder setEmpty(boolean value) {
      
      empty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool empty = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmpty() {
      
      empty_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientPagePRT)
  }

  // @@protoc_insertion_point(class_scope:ClientPagePRT)
  private static final org.devolpex.backend.stubs.client.ClientPagePRT DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.devolpex.backend.stubs.client.ClientPagePRT();
  }

  public static org.devolpex.backend.stubs.client.ClientPagePRT getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientPagePRT>
      PARSER = new com.google.protobuf.AbstractParser<ClientPagePRT>() {
    @java.lang.Override
    public ClientPagePRT parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientPagePRT(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientPagePRT> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientPagePRT> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.devolpex.backend.stubs.client.ClientPagePRT getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

