// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface CreateClientREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateClientREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientRequestPRT client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ClientRequestPRT client = 1;</code>
   * @return The client.
   */
  org.devolpex.backend.stubs.client.ClientRequestPRT getClient();
  /**
   * <code>.ClientRequestPRT client = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientRequestPRTOrBuilder getClientOrBuilder();
}
