// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface FetchClientByIdRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchClientByIdRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientPRT client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ClientPRT client = 1;</code>
   * @return The client.
   */
  org.devolpex.backend.stubs.client.ClientPRT getClient();
  /**
   * <code>.ClientPRT client = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPRTOrBuilder getClientOrBuilder();
}
