// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface FetchPageClientsRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchPageClientsRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientPagePRT data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.ClientPagePRT data = 1;</code>
   * @return The data.
   */
  org.devolpex.backend.stubs.client.ClientPagePRT getData();
  /**
   * <code>.ClientPagePRT data = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPagePRTOrBuilder getDataOrBuilder();
}
