// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface FetchPageClientsREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchPageClientsREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string orderBy = 3;</code>
   * @return The orderBy.
   */
  java.lang.String getOrderBy();
  /**
   * <code>string orderBy = 3;</code>
   * @return The bytes for orderBy.
   */
  com.google.protobuf.ByteString
      getOrderByBytes();

  /**
   * <code>string sortBy = 4;</code>
   * @return The sortBy.
   */
  java.lang.String getSortBy();
  /**
   * <code>string sortBy = 4;</code>
   * @return The bytes for sortBy.
   */
  com.google.protobuf.ByteString
      getSortByBytes();
}
