// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface FetchListClientsRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchListClientsRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ClientPRT clients = 1;</code>
   */
  java.util.List<org.devolpex.backend.stubs.client.ClientPRT> 
      getClientsList();
  /**
   * <code>repeated .ClientPRT clients = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPRT getClients(int index);
  /**
   * <code>repeated .ClientPRT clients = 1;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .ClientPRT clients = 1;</code>
   */
  java.util.List<? extends org.devolpex.backend.stubs.client.ClientPRTOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .ClientPRT clients = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientPRTOrBuilder getClientsOrBuilder(
      int index);
}
