// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface ReservationPRTOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationPRT)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 4;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 4;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();

  /**
   * <code>.ChambrePRT chambre = 6;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.ChambrePRT chambre = 6;</code>
   * @return The chambre.
   */
  org.devolpex.backend.stubs.client.ChambrePRT getChambre();
  /**
   * <code>.ChambrePRT chambre = 6;</code>
   */
  org.devolpex.backend.stubs.client.ChambrePRTOrBuilder getChambreOrBuilder();
}
