// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package org.devolpex.backend.stubs.client;

public interface UpdateClientREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateClientREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.ClientRequestPRT client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ClientRequestPRT client = 2;</code>
   * @return The client.
   */
  org.devolpex.backend.stubs.client.ClientRequestPRT getClient();
  /**
   * <code>.ClientRequestPRT client = 2;</code>
   */
  org.devolpex.backend.stubs.client.ClientRequestPRTOrBuilder getClientOrBuilder();
}
