// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public interface GetReservationPageRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationPageRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ReservationPage reservationPage = 1;</code>
   * @return Whether the reservationPage field is set.
   */
  boolean hasReservationPage();
  /**
   * <code>.ReservationPage reservationPage = 1;</code>
   * @return The reservationPage.
   */
  org.devolpex.backend.stubs.reservation.ReservationPage getReservationPage();
  /**
   * <code>.ReservationPage reservationPage = 1;</code>
   */
  org.devolpex.backend.stubs.reservation.ReservationPageOrBuilder getReservationPageOrBuilder();
}
