// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public interface GetReservationsListREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsListREQ)
    com.google.protobuf.MessageOrBuilder {
}
