// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public interface GetReservationByIdREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
