// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsListREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsListREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsListRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsListRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationPageREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationPageREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationPageRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationPageRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pageable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pageable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sort_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sort_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationPage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationPage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\032\014client.proto\032\rchamb" +
      "re.proto\032\037google/protobuf/timestamp.prot" +
      "o\"\206\001\n\013Reservation\022\n\n\002id\030\001 \001(\003\022\027\n\006client\030" +
      "\002 \001(\0132\007.Client\022\031\n\007chambre\030\003 \001(\0132\010.Chambr" +
      "e\022\021\n\tdateDebut\030\004 \001(\t\022\017\n\007dateFin\030\005 \001(\t\022\023\n" +
      "\013preferences\030\006 \001(\t\"\030\n\026GetReservationsLis" +
      "tREQ\"<\n\026GetReservationsListRES\022\"\n\014reserv" +
      "ations\030\001 \003(\0132\014.Reservation\"T\n\025GetReserva" +
      "tionPageREQ\022\014\n\004page\030\001 \001(\005\022\014\n\004size\030\002 \001(\005\022" +
      "\017\n\007orderBy\030\003 \001(\t\022\016\n\006sortBy\030\004 \001(\t\"B\n\025GetR" +
      "eservationPageRES\022)\n\017reservationPage\030\001 \001" +
      "(\0132\020.ReservationPage\"#\n\025GetReservationBy" +
      "IdREQ\022\n\n\002id\030\001 \001(\003\":\n\025GetReservationByIdR" +
      "ES\022!\n\013reservation\030\001 \001(\0132\014.Reservation\"\255\001" +
      "\n\016ReservationREQ\022\027\n\006client\030\001 \001(\0132\007.Clien" +
      "t\022\021\n\tchambreId\030\002 \001(\003\022-\n\tdateDebut\030\003 \001(\0132" +
      "\032.google.protobuf.Timestamp\022+\n\007dateFin\030\004" +
      " \001(\0132\032.google.protobuf.Timestamp\022\023\n\013pref" +
      "erences\030\005 \001(\t\"3\n\016ReservationRES\022!\n\013reser" +
      "vation\030\001 \001(\0132\014.Reservation\"H\n\024UpdateRese" +
      "rvationREQ\022\n\n\002id\030\001 \001(\003\022$\n\013reservation\030\002 " +
      "\001(\0132\017.ReservationREQ\"\"\n\024DeleteReservatio" +
      "nREQ\022\n\n\002id\030\001 \001(\003\"u\n\010Pageable\022\022\n\npageNumb" +
      "er\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\016\n\006offset\030\003 \001" +
      "(\003\022\r\n\005paged\030\004 \001(\010\022\017\n\007unpaged\030\005 \001(\010\022\023\n\004so" +
      "rt\030\006 \001(\0132\005.Sort\"7\n\004Sort\022\016\n\006sorted\030\001 \001(\010\022" +
      "\020\n\010unsorted\030\002 \001(\010\022\r\n\005empty\030\003 \001(\010\"\334\001\n\017Res" +
      "ervationPage\022\035\n\007content\030\001 \003(\0132\014.Reservat" +
      "ion\022\033\n\010pageable\030\002 \001(\0132\t.Pageable\022\025\n\rtota" +
      "lElements\030\003 \001(\003\022\022\n\ntotalPages\030\004 \001(\005\022\014\n\004l" +
      "ast\030\005 \001(\010\022\r\n\005first\030\006 \001(\010\022\014\n\004size\030\007 \001(\005\022\016" +
      "\n\006number\030\010 \001(\005\022\030\n\020numberOfElements\030\t \001(\005" +
      "\022\r\n\005empty\030\n \001(\010B*\n&org.devolpex.backend." +
      "stubs.reservationP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor(),
          org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "Client", "Chambre", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetReservationsListREQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetReservationsListREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsListREQ_descriptor,
        new java.lang.String[] { });
    internal_static_GetReservationsListRES_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetReservationsListRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsListRES_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetReservationPageREQ_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetReservationPageREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationPageREQ_descriptor,
        new java.lang.String[] { "Page", "Size", "OrderBy", "SortBy", });
    internal_static_GetReservationPageRES_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetReservationPageRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationPageRES_descriptor,
        new java.lang.String[] { "ReservationPage", });
    internal_static_GetReservationByIdREQ_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationByIdREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdREQ_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdRES_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetReservationByIdRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRES_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_ReservationREQ_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ReservationREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationREQ_descriptor,
        new java.lang.String[] { "Client", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_ReservationRES_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ReservationRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRES_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_UpdateReservationREQ_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateReservationREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationREQ_descriptor,
        new java.lang.String[] { "Id", "Reservation", });
    internal_static_DeleteReservationREQ_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteReservationREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationREQ_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Pageable_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Pageable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pageable_descriptor,
        new java.lang.String[] { "PageNumber", "PageSize", "Offset", "Paged", "Unpaged", "Sort", });
    internal_static_Sort_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Sort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sort_descriptor,
        new java.lang.String[] { "Sorted", "Unsorted", "Empty", });
    internal_static_ReservationPage_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ReservationPage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationPage_descriptor,
        new java.lang.String[] { "Content", "Pageable", "TotalElements", "TotalPages", "Last", "First", "Size", "Number", "NumberOfElements", "Empty", });
    org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor();
    org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
