// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

/**
 * <pre>
 * Create Reservation 
 * </pre>
 *
 * Protobuf type {@code ReservationREQ}
 */
public  final class ReservationREQ extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReservationREQ)
    ReservationREQOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationREQ.newBuilder() to construct.
  private ReservationREQ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationREQ() {
    preferences_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReservationREQ();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationREQ(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.devolpex.backend.stubs.client.Client.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(org.devolpex.backend.stubs.client.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            chambreId_ = input.readInt64();
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateDebut_ != null) {
              subBuilder = dateDebut_.toBuilder();
            }
            dateDebut_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateDebut_);
              dateDebut_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateFin_ != null) {
              subBuilder = dateFin_.toBuilder();
            }
            dateFin_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateFin_);
              dateFin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            preferences_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.devolpex.backend.stubs.reservation.ReservationOuterClass.internal_static_ReservationREQ_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.devolpex.backend.stubs.reservation.ReservationOuterClass.internal_static_ReservationREQ_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.devolpex.backend.stubs.reservation.ReservationREQ.class, org.devolpex.backend.stubs.reservation.ReservationREQ.Builder.class);
  }

  public static final int CLIENT_FIELD_NUMBER = 1;
  private org.devolpex.backend.stubs.client.Client client_;
  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  public org.devolpex.backend.stubs.client.Client getClient() {
    return client_ == null ? org.devolpex.backend.stubs.client.Client.getDefaultInstance() : client_;
  }
  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   */
  public org.devolpex.backend.stubs.client.ClientOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int CHAMBREID_FIELD_NUMBER = 2;
  private long chambreId_;
  /**
   * <pre>
   * The chambre ID
   * </pre>
   *
   * <code>int64 chambreId = 2;</code>
   * @return The chambreId.
   */
  public long getChambreId() {
    return chambreId_;
  }

  public static final int DATEDEBUT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp dateDebut_;
  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   * @return Whether the dateDebut field is set.
   */
  public boolean hasDateDebut() {
    return dateDebut_ != null;
  }
  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   * @return The dateDebut.
   */
  public com.google.protobuf.Timestamp getDateDebut() {
    return dateDebut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
  }
  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateDebutOrBuilder() {
    return getDateDebut();
  }

  public static final int DATEFIN_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp dateFin_;
  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   * @return Whether the dateFin field is set.
   */
  public boolean hasDateFin() {
    return dateFin_ != null;
  }
  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   * @return The dateFin.
   */
  public com.google.protobuf.Timestamp getDateFin() {
    return dateFin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
  }
  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateFinOrBuilder() {
    return getDateFin();
  }

  public static final int PREFERENCES_FIELD_NUMBER = 5;
  private volatile java.lang.Object preferences_;
  /**
   * <pre>
   * Preferences, up to 255 characters
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The preferences.
   */
  public java.lang.String getPreferences() {
    java.lang.Object ref = preferences_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preferences_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Preferences, up to 255 characters
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The bytes for preferences.
   */
  public com.google.protobuf.ByteString
      getPreferencesBytes() {
    java.lang.Object ref = preferences_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preferences_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (client_ != null) {
      output.writeMessage(1, getClient());
    }
    if (chambreId_ != 0L) {
      output.writeInt64(2, chambreId_);
    }
    if (dateDebut_ != null) {
      output.writeMessage(3, getDateDebut());
    }
    if (dateFin_ != null) {
      output.writeMessage(4, getDateFin());
    }
    if (!getPreferencesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, preferences_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClient());
    }
    if (chambreId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, chambreId_);
    }
    if (dateDebut_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDateDebut());
    }
    if (dateFin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDateFin());
    }
    if (!getPreferencesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, preferences_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.devolpex.backend.stubs.reservation.ReservationREQ)) {
      return super.equals(obj);
    }
    org.devolpex.backend.stubs.reservation.ReservationREQ other = (org.devolpex.backend.stubs.reservation.ReservationREQ) obj;

    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (!getClient()
          .equals(other.getClient())) return false;
    }
    if (getChambreId()
        != other.getChambreId()) return false;
    if (hasDateDebut() != other.hasDateDebut()) return false;
    if (hasDateDebut()) {
      if (!getDateDebut()
          .equals(other.getDateDebut())) return false;
    }
    if (hasDateFin() != other.hasDateFin()) return false;
    if (hasDateFin()) {
      if (!getDateFin()
          .equals(other.getDateFin())) return false;
    }
    if (!getPreferences()
        .equals(other.getPreferences())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    hash = (37 * hash) + CHAMBREID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChambreId());
    if (hasDateDebut()) {
      hash = (37 * hash) + DATEDEBUT_FIELD_NUMBER;
      hash = (53 * hash) + getDateDebut().hashCode();
    }
    if (hasDateFin()) {
      hash = (37 * hash) + DATEFIN_FIELD_NUMBER;
      hash = (53 * hash) + getDateFin().hashCode();
    }
    hash = (37 * hash) + PREFERENCES_FIELD_NUMBER;
    hash = (53 * hash) + getPreferences().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.devolpex.backend.stubs.reservation.ReservationREQ parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.devolpex.backend.stubs.reservation.ReservationREQ prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Create Reservation 
   * </pre>
   *
   * Protobuf type {@code ReservationREQ}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReservationREQ)
      org.devolpex.backend.stubs.reservation.ReservationREQOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.devolpex.backend.stubs.reservation.ReservationOuterClass.internal_static_ReservationREQ_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.devolpex.backend.stubs.reservation.ReservationOuterClass.internal_static_ReservationREQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.devolpex.backend.stubs.reservation.ReservationREQ.class, org.devolpex.backend.stubs.reservation.ReservationREQ.Builder.class);
    }

    // Construct using org.devolpex.backend.stubs.reservation.ReservationREQ.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      chambreId_ = 0L;

      if (dateDebutBuilder_ == null) {
        dateDebut_ = null;
      } else {
        dateDebut_ = null;
        dateDebutBuilder_ = null;
      }
      if (dateFinBuilder_ == null) {
        dateFin_ = null;
      } else {
        dateFin_ = null;
        dateFinBuilder_ = null;
      }
      preferences_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.devolpex.backend.stubs.reservation.ReservationOuterClass.internal_static_ReservationREQ_descriptor;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.reservation.ReservationREQ getDefaultInstanceForType() {
      return org.devolpex.backend.stubs.reservation.ReservationREQ.getDefaultInstance();
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.reservation.ReservationREQ build() {
      org.devolpex.backend.stubs.reservation.ReservationREQ result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.devolpex.backend.stubs.reservation.ReservationREQ buildPartial() {
      org.devolpex.backend.stubs.reservation.ReservationREQ result = new org.devolpex.backend.stubs.reservation.ReservationREQ(this);
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      result.chambreId_ = chambreId_;
      if (dateDebutBuilder_ == null) {
        result.dateDebut_ = dateDebut_;
      } else {
        result.dateDebut_ = dateDebutBuilder_.build();
      }
      if (dateFinBuilder_ == null) {
        result.dateFin_ = dateFin_;
      } else {
        result.dateFin_ = dateFinBuilder_.build();
      }
      result.preferences_ = preferences_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.devolpex.backend.stubs.reservation.ReservationREQ) {
        return mergeFrom((org.devolpex.backend.stubs.reservation.ReservationREQ)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.devolpex.backend.stubs.reservation.ReservationREQ other) {
      if (other == org.devolpex.backend.stubs.reservation.ReservationREQ.getDefaultInstance()) return this;
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (other.getChambreId() != 0L) {
        setChambreId(other.getChambreId());
      }
      if (other.hasDateDebut()) {
        mergeDateDebut(other.getDateDebut());
      }
      if (other.hasDateFin()) {
        mergeDateFin(other.getDateFin());
      }
      if (!other.getPreferences().isEmpty()) {
        preferences_ = other.preferences_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.devolpex.backend.stubs.reservation.ReservationREQ parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.devolpex.backend.stubs.reservation.ReservationREQ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.devolpex.backend.stubs.client.Client client_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.client.Client, org.devolpex.backend.stubs.client.Client.Builder, org.devolpex.backend.stubs.client.ClientOrBuilder> clientBuilder_;
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     * @return The client.
     */
    public org.devolpex.backend.stubs.client.Client getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? org.devolpex.backend.stubs.client.Client.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public Builder setClient(org.devolpex.backend.stubs.client.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public Builder setClient(
        org.devolpex.backend.stubs.client.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public Builder mergeClient(org.devolpex.backend.stubs.client.Client value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            org.devolpex.backend.stubs.client.Client.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public org.devolpex.backend.stubs.client.Client.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    public org.devolpex.backend.stubs.client.ClientOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            org.devolpex.backend.stubs.client.Client.getDefaultInstance() : client_;
      }
    }
    /**
     * <pre>
     * The client information
     * </pre>
     *
     * <code>.Client client = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.devolpex.backend.stubs.client.Client, org.devolpex.backend.stubs.client.Client.Builder, org.devolpex.backend.stubs.client.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.devolpex.backend.stubs.client.Client, org.devolpex.backend.stubs.client.Client.Builder, org.devolpex.backend.stubs.client.ClientOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private long chambreId_ ;
    /**
     * <pre>
     * The chambre ID
     * </pre>
     *
     * <code>int64 chambreId = 2;</code>
     * @return The chambreId.
     */
    public long getChambreId() {
      return chambreId_;
    }
    /**
     * <pre>
     * The chambre ID
     * </pre>
     *
     * <code>int64 chambreId = 2;</code>
     * @param value The chambreId to set.
     * @return This builder for chaining.
     */
    public Builder setChambreId(long value) {
      
      chambreId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The chambre ID
     * </pre>
     *
     * <code>int64 chambreId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChambreId() {
      
      chambreId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateDebut_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateDebutBuilder_;
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     * @return Whether the dateDebut field is set.
     */
    public boolean hasDateDebut() {
      return dateDebutBuilder_ != null || dateDebut_ != null;
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     * @return The dateDebut.
     */
    public com.google.protobuf.Timestamp getDateDebut() {
      if (dateDebutBuilder_ == null) {
        return dateDebut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
      } else {
        return dateDebutBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public Builder setDateDebut(com.google.protobuf.Timestamp value) {
      if (dateDebutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateDebut_ = value;
        onChanged();
      } else {
        dateDebutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public Builder setDateDebut(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateDebutBuilder_ == null) {
        dateDebut_ = builderForValue.build();
        onChanged();
      } else {
        dateDebutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public Builder mergeDateDebut(com.google.protobuf.Timestamp value) {
      if (dateDebutBuilder_ == null) {
        if (dateDebut_ != null) {
          dateDebut_ =
            com.google.protobuf.Timestamp.newBuilder(dateDebut_).mergeFrom(value).buildPartial();
        } else {
          dateDebut_ = value;
        }
        onChanged();
      } else {
        dateDebutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public Builder clearDateDebut() {
      if (dateDebutBuilder_ == null) {
        dateDebut_ = null;
        onChanged();
      } else {
        dateDebut_ = null;
        dateDebutBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateDebutBuilder() {
      
      onChanged();
      return getDateDebutFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateDebutOrBuilder() {
      if (dateDebutBuilder_ != null) {
        return dateDebutBuilder_.getMessageOrBuilder();
      } else {
        return dateDebut_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
      }
    }
    /**
     * <pre>
     * The start date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateDebutFieldBuilder() {
      if (dateDebutBuilder_ == null) {
        dateDebutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateDebut(),
                getParentForChildren(),
                isClean());
        dateDebut_ = null;
      }
      return dateDebutBuilder_;
    }

    private com.google.protobuf.Timestamp dateFin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateFinBuilder_;
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     * @return Whether the dateFin field is set.
     */
    public boolean hasDateFin() {
      return dateFinBuilder_ != null || dateFin_ != null;
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     * @return The dateFin.
     */
    public com.google.protobuf.Timestamp getDateFin() {
      if (dateFinBuilder_ == null) {
        return dateFin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
      } else {
        return dateFinBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public Builder setDateFin(com.google.protobuf.Timestamp value) {
      if (dateFinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateFin_ = value;
        onChanged();
      } else {
        dateFinBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public Builder setDateFin(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateFinBuilder_ == null) {
        dateFin_ = builderForValue.build();
        onChanged();
      } else {
        dateFinBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public Builder mergeDateFin(com.google.protobuf.Timestamp value) {
      if (dateFinBuilder_ == null) {
        if (dateFin_ != null) {
          dateFin_ =
            com.google.protobuf.Timestamp.newBuilder(dateFin_).mergeFrom(value).buildPartial();
        } else {
          dateFin_ = value;
        }
        onChanged();
      } else {
        dateFinBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public Builder clearDateFin() {
      if (dateFinBuilder_ == null) {
        dateFin_ = null;
        onChanged();
      } else {
        dateFin_ = null;
        dateFinBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateFinBuilder() {
      
      onChanged();
      return getDateFinFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateFinOrBuilder() {
      if (dateFinBuilder_ != null) {
        return dateFinBuilder_.getMessageOrBuilder();
      } else {
        return dateFin_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
      }
    }
    /**
     * <pre>
     * The end date (must be in the future)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFinFieldBuilder() {
      if (dateFinBuilder_ == null) {
        dateFinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateFin(),
                getParentForChildren(),
                isClean());
        dateFin_ = null;
      }
      return dateFinBuilder_;
    }

    private java.lang.Object preferences_ = "";
    /**
     * <pre>
     * Preferences, up to 255 characters
     * </pre>
     *
     * <code>string preferences = 5;</code>
     * @return The preferences.
     */
    public java.lang.String getPreferences() {
      java.lang.Object ref = preferences_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preferences_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Preferences, up to 255 characters
     * </pre>
     *
     * <code>string preferences = 5;</code>
     * @return The bytes for preferences.
     */
    public com.google.protobuf.ByteString
        getPreferencesBytes() {
      java.lang.Object ref = preferences_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preferences_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Preferences, up to 255 characters
     * </pre>
     *
     * <code>string preferences = 5;</code>
     * @param value The preferences to set.
     * @return This builder for chaining.
     */
    public Builder setPreferences(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preferences_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Preferences, up to 255 characters
     * </pre>
     *
     * <code>string preferences = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferences() {
      
      preferences_ = getDefaultInstance().getPreferences();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Preferences, up to 255 characters
     * </pre>
     *
     * <code>string preferences = 5;</code>
     * @param value The bytes for preferences to set.
     * @return This builder for chaining.
     */
    public Builder setPreferencesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preferences_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReservationREQ)
  }

  // @@protoc_insertion_point(class_scope:ReservationREQ)
  private static final org.devolpex.backend.stubs.reservation.ReservationREQ DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.devolpex.backend.stubs.reservation.ReservationREQ();
  }

  public static org.devolpex.backend.stubs.reservation.ReservationREQ getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationREQ>
      PARSER = new com.google.protobuf.AbstractParser<ReservationREQ>() {
    @java.lang.Override
    public ReservationREQ parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationREQ(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationREQ> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationREQ> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.devolpex.backend.stubs.reservation.ReservationREQ getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

