// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public interface ReservationREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  org.devolpex.backend.stubs.client.Client getClient();
  /**
   * <pre>
   * The client information
   * </pre>
   *
   * <code>.Client client = 1;</code>
   */
  org.devolpex.backend.stubs.client.ClientOrBuilder getClientOrBuilder();

  /**
   * <pre>
   * The chambre ID
   * </pre>
   *
   * <code>int64 chambreId = 2;</code>
   * @return The chambreId.
   */
  long getChambreId();

  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   * @return Whether the dateDebut field is set.
   */
  boolean hasDateDebut();
  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   * @return The dateDebut.
   */
  com.google.protobuf.Timestamp getDateDebut();
  /**
   * <pre>
   * The start date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateDebutOrBuilder();

  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   * @return Whether the dateFin field is set.
   */
  boolean hasDateFin();
  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   * @return The dateFin.
   */
  com.google.protobuf.Timestamp getDateFin();
  /**
   * <pre>
   * The end date (must be in the future)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateFinOrBuilder();

  /**
   * <pre>
   * Preferences, up to 255 characters
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <pre>
   * Preferences, up to 255 characters
   * </pre>
   *
   * <code>string preferences = 5;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
