// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsListREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsListREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsListRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsListRES_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\032\014client.proto\032\rchamb" +
      "re.proto\"\206\001\n\013Reservation\022\n\n\002id\030\001 \001(\003\022\027\n\006" +
      "client\030\002 \001(\0132\007.Client\022\031\n\007chambre\030\003 \001(\0132\010" +
      ".Chambre\022\021\n\tdateDebut\030\004 \001(\t\022\017\n\007dateFin\030\005" +
      " \001(\t\022\023\n\013preferences\030\006 \001(\t\"\030\n\026GetReservat" +
      "ionsListREQ\"<\n\026GetReservationsListRES\022\"\n" +
      "\014reservations\030\001 \003(\0132\014.ReservationB*\n&org" +
      ".devolpex.backend.stubs.reservationP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor(),
          org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor(),
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "Client", "Chambre", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetReservationsListREQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetReservationsListREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsListREQ_descriptor,
        new java.lang.String[] { });
    internal_static_GetReservationsListRES_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetReservationsListRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsListRES_descriptor,
        new java.lang.String[] { "Reservations", });
    org.devolpex.backend.stubs.client.ClientOuterClass.getDescriptor();
    org.devolpex.backend.stubs.chambre.ChambreOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
