// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package org.devolpex.backend.stubs.reservation;

public interface SortOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Sort)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool sorted = 1;</code>
   * @return The sorted.
   */
  boolean getSorted();

  /**
   * <code>bool unsorted = 2;</code>
   * @return The unsorted.
   */
  boolean getUnsorted();

  /**
   * <code>bool empty = 3;</code>
   * @return The empty.
   */
  boolean getEmpty();
}
