spring:
  application:
    name: hotel-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphiql:
    endpoint: /graphql
    enabled: true
server:
  port: 8082
grpc:
  server:
    port: 9099
# Logging
logging:
  org.springframework.web: TRACE

# Swagger
swagger:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# GraphiQL
# Spring Boot Actuator (for Prometheus, Loki, Grafana integration)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus  # Exposes relevant endpoints for Prometheus/Grafana
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true  # Enables histogram for HTTP request metrics
  observations:
    key-values:
      application: hotel-backend  # Can be customized with your application name
  tracing:
    sampling:
      probability: 1.0  # Enables tracing for all requests
  # Prometheus scraping
# This configuration allows Prometheus to scrape metrics from the `/actuator/prometheus` endpoint

  prometheus:
    enabled: true  # Ensure that Prometheus metrics are enabled

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173
