spring:
  application:
    name: hotel-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphiql:
    endpoint: /graphql
    enabled: true
server:
  port: 8082
grpc:
  server:
    port: 9099
logging:
  org.springframework.web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  prometheus:
    enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
